-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "chatGDP"."user"
(
    id uuid NOT NULL,
    first_name "char"[] NOT NULL,
    last_name "char"[] NOT NULL,
    create_date date NOT NULL,
    is_active "char" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "chatGDP".user_group
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    group_id uuid NOT NULL,
    create_date date NOT NULL,
    is_active "char" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "chatGDP"."group"
(
    id uuid NOT NULL,
    name "char"[] NOT NULL,
    create_date date NOT NULL,
    is_active "char" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "chatGDP".message
(
    id uuid NOT NULL,
    subject "char"[],
    creator_id uuid NOT NULL,
    message_body text,
    create_date date NOT NULL,
    parent_message_id uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "chatGDP".message_recipient
(
    id uuid NOT NULL,
    recipient_id uuid NOT NULL,
    recipient_group_id uuid NOT NULL,
    message_id uuid NOT NULL,
    is_read numeric NOT NULL,
    PRIMARY KEY (is_read)
);

ALTER TABLE IF EXISTS "chatGDP".user_group
    ADD CONSTRAINT uder_id FOREIGN KEY (user_id)
    REFERENCES "chatGDP"."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "chatGDP".user_group
    ADD CONSTRAINT group_id FOREIGN KEY (group_id)
    REFERENCES "chatGDP"."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "chatGDP".message
    ADD CONSTRAINT parent_message_id FOREIGN KEY (parent_message_id)
    REFERENCES "chatGDP".message (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "chatGDP".message
    ADD CONSTRAINT creator_id FOREIGN KEY (creator_id)
    REFERENCES "chatGDP"."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "chatGDP".message_recipient
    ADD CONSTRAINT recipient_id FOREIGN KEY (recipient_id)
    REFERENCES "chatGDP"."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "chatGDP".message_recipient
    ADD CONSTRAINT recipient_group_id FOREIGN KEY (recipient_group_id)
    REFERENCES "chatGDP".user_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "chatGDP".message_recipient
    ADD CONSTRAINT message_id FOREIGN KEY (message_id)
    REFERENCES "chatGDP".message (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;